// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTask.Infrastructure.Data;

#nullable disable

namespace TestTask.Infrastructure.Migrations
{
    [DbContext(typeof(WeightingContext))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Domain.WeightingAggregate.Weighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("WeightNetKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Weightings");
                });

            modelBuilder.Entity("TestTask.Domain.WeightingAggregate.Weighting", b =>
                {
                    b.OwnsOne("TestTask.Domain.WeightingAggregate.CarNumber", "CarNumber", b1 =>
                        {
                            b1.Property<int>("WeightingId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WeightingId");

                            b1.ToTable("Weightings");

                            b1.WithOwner()
                                .HasForeignKey("WeightingId");
                        });

                    b.OwnsOne("TestTask.Domain.WeightingAggregate.WeightingGross", "WeightingGross", b1 =>
                        {
                            b1.Property<int>("WeightingId")
                                .HasColumnType("integer");

                            b1.Property<double>("WeightKg")
                                .HasColumnType("double precision");

                            b1.Property<DateTime>("WeightTime")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("WeightingId");

                            b1.ToTable("Weightings");

                            b1.WithOwner()
                                .HasForeignKey("WeightingId");
                        });

                    b.OwnsOne("TestTask.Domain.WeightingAggregate.WeightingTare", "WeightingTare", b1 =>
                        {
                            b1.Property<int>("WeightingId")
                                .HasColumnType("integer");

                            b1.Property<double>("WeightKg")
                                .HasColumnType("double precision");

                            b1.Property<DateTime>("WeightTime")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("WeightingId");

                            b1.ToTable("Weightings");

                            b1.WithOwner()
                                .HasForeignKey("WeightingId");
                        });

                    b.Navigation("CarNumber")
                        .IsRequired();

                    b.Navigation("WeightingGross")
                        .IsRequired();

                    b.Navigation("WeightingTare");
                });
#pragma warning restore 612, 618
        }
    }
}
